[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10000
via_ir = true
evm_version = "cancun"
gas_limit = "18446744073709551615"
fs_permissions = [{ access = "read", path = "./test/fixtures" }]
memory_limit = 1073741824
