"""Write the data files of the Cardputer firmware from the web demo's data block.

    python scripts/build_firmware.py [--out DIR]

firmware/cardputer/lib/c3s_core/c3s_data.{h,c} hold the core and policy netlists exactly
as docs/demo/index.html embeds them (scripts/build_demo.py writes that block from the
committed manifests), their SHA-256, the encoding edges, the motor timing and the
reference episodes. The firmware hashes the bytes and replays the episodes at boot, so
the device and the page check the same netlists against the same Python-computed ticks.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "docs" / "demo" / "index.html"
OUT = ROOT / "firmware" / "cardputer" / "lib" / "c3s_core"
BEGIN, END = "<!-- DATA:BEGIN -->", "<!-- DATA:END -->"
NOTICE = "/* Generated by scripts/build_firmware.py from the data block of docs/demo/index.html. Do not edit. */\n"


def demo_data() -> dict:
    block = PAGE.read_text().split(BEGIN)[1].split(END)[0]
    return json.loads(block[block.index("{") : block.rindex("}") + 1])


def c_double(v: float) -> str:
    return repr(float(v))


def c_rows(items: list[str], per_line: int) -> str:
    return "\n".join("  " + ", ".join(items[i : i + per_line]) + "," for i in range(0, len(items), per_line))


def circuit(entry: dict, prefix: str) -> tuple[bytes, list[tuple[str, object]]]:
    raw = bytes.fromhex(entry["hex"].removeprefix("0x"))
    if hashlib.sha256(raw).hexdigest() != entry["sha256"]:
        raise SystemExit(f"{entry['name']}: the demo's hash does not match its bytes")
    defines = [
        (f"{prefix}_NAME", json.dumps(entry["name"])),
        (f"{prefix}_INPUTS", len(entry["inputs"])),
        (f"{prefix}_OUTPUTS", len(entry["outputs"])),
        (f"{prefix}_LATCHES", entry["nState"]),
        (f"{prefix}_NAND", entry["metrics"]["nand"]),
        (f"{prefix}_DEPTH", entry["metrics"]["depth"]),
        (f"{prefix}_BYTES", len(raw)),
        (f"{prefix}_SHA256", json.dumps(entry["sha256"])),
    ]
    return raw, defines


def render(d: dict) -> tuple[str, str]:
    core, core_defines = circuit(d["core"], "C3S_CORE")
    policy, policy_defines = circuit(d["policy"], "C3S_POLICY")
    enc, teacher, stim, layout = d["encoding"], d["teacher"], d["stimulus"], d["core"]["stateLayout"]
    levels = 1 << enc["bits"]
    if not len(enc["sizeEdges"]) == len(enc["speedEdges"]) == levels:
        raise SystemExit("encoding edges do not match the bit width")
    motor_names = [d["motorNames"][str(k)] for k in range(4)]
    defines = core_defines + policy_defines + [
        ("C3S_BITS", enc["bits"]),
        ("C3S_LEVELS", levels),
        ("C3S_FEATURES", 4 * enc["bits"]),
        ("C3S_RAISE_BITS", layout["raise_counter_bits"]),
        ("C3S_REFRACTORY_BITS", layout["refractory_bits"]),
        ("C3S_WING_RAISE_TICKS", teacher["wingRaiseTicks"]),
        ("C3S_REFRACTORY_TICKS", teacher["refractoryTicks"]),
        ("C3S_TICK_MS", c_double(teacher["tickMs"])),
        ("C3S_START_DEG", c_double(stim["startDeg"])),
        ("C3S_END_DEG", c_double(stim["endDeg"])),
        ("C3S_OVERLAP_DEG", c_double(stim["binocularOverlapDeg"])),
        ("C3S_EPISODES", len(d["episodes"])),
    ]
    width = max(len(k) for k, _ in defines)
    header = NOTICE + "#ifndef C3S_DATA_H\n#define C3S_DATA_H\n\n#include \"c3s_core.h\"\n\n"
    header += "".join(f"#define {k:<{width}} {v}\n" for k, v in defines)
    header += (
        "\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        "extern const uint8_t c3s_core_netlist[C3S_CORE_BYTES];\n"
        "extern const uint8_t c3s_policy_netlist[C3S_POLICY_BYTES];\n"
        "extern const double c3s_size_edges[C3S_LEVELS];\n"
        "extern const double c3s_speed_edges[C3S_LEVELS];\n"
        "extern const c3s_ref_episode c3s_episodes[C3S_EPISODES];\n"
        "extern const char *const c3s_motor_names[4];\n"
        "\n#ifdef __cplusplus\n}\n#endif\n\n#endif\n"
    )

    source = [NOTICE, '#include "c3s_data.h"\n']
    for name, raw in (("core", core), ("policy", policy)):
        source.append(f"\nconst uint8_t c3s_{name}_netlist[C3S_{name.upper()}_BYTES] = {{\n")
        source.append(c_rows([f"0x{b:02x}" for b in raw], 12) + "\n};\n")
    for name, key in (("size", "sizeEdges"), ("speed", "speedEdges")):
        source.append(f"\nconst double c3s_{name}_edges[C3S_LEVELS] = {{\n{c_rows([c_double(v) for v in enc[key]], 4)}\n}};\n")
    entries = []
    for i, e in enumerate(d["episodes"]):
        pairs = [f"{c_double(th)}, {c_double(dth)}" for th, dth in e["samples"]]
        ticks = [f"{{0x{x:05x}, {motor}, {state}}}" for x, motor, state in e["ticks"]]
        source.append(f"\n/* l/v {e['lv']:g} ms, azimuth {e['azimuth']:g} deg */\n")
        source.append(f"static const double samples_{i}[] = {{\n{c_rows(pairs, 2)}\n}};\n")
        source.append(f"static const c3s_ref_tick ticks_{i}[] = {{\n{c_rows(ticks, 4)}\n}};\n")
        entries.append(f"  {{{c_double(e['lv'])}, {c_double(e['azimuth'])}, {len(pairs)}, samples_{i}, {len(ticks)}, ticks_{i}}},")
    source.append("\nconst c3s_ref_episode c3s_episodes[C3S_EPISODES] = {\n" + "\n".join(entries) + "\n};\n")
    source.append("\nconst char *const c3s_motor_names[4] = {" + ", ".join(json.dumps(n) for n in motor_names) + "};\n")
    return header, "".join(source)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=OUT, help="directory for c3s_data.h and c3s_data.c")
    args = ap.parse_args()
    d = demo_data()
    header, source = render(d)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "c3s_data.h").write_text(header)
    (args.out / "c3s_data.c").write_text(source)
    print(f"wrote {d['core']['name']}, {d['policy']['name']} and {len(d['episodes'])} reference episodes to {args.out}")


if __name__ == "__main__":
    main()
