"""The real cells, for the Cardputer: docs/sim/skeletons.{bin,json} as a C header.

    python scripts/build_firmware_brain.py      # writes firmware/cardputer/src/c3s_brain.h

The simulator page already draws 26 cells from the MaleCNS v1.0 release (both giant
fibers, and per fiber its six strongest LC4 and six strongest LPLC2 inputs; see
scripts/build_sim_skeletons.py). This puts the same geometry on the device, so its
brain view is the published cells rather than a drawing of a brain.

Positions are the page's unit-box coordinates quantised to int8 (x127): at 240x135
pixels a step of 1/127 of the box is below a pixel. Segments stay as index pairs.
Nothing is added, moved or smoothed.

The outline drawn behind the cells is derived here too, and is marked as such on the
device: per side, an ellipse at the LC4+LPLC2 centroid with radii of 2.5 standard
deviations of those points (where the lobula is), and between them an ellipse spanning
the gap between the two lobes at the same depth, as tall as the giant fibers' extent
within that slab. It shows where these cells are; it is not a neuropil mesh.

MaleCNS is CC-BY; see NOTICE.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SKEL_JSON = ROOT / "docs" / "sim" / "skeletons.json"
SKEL_BIN = ROOT / "docs" / "sim" / "skeletons.bin"
OUT = ROOT / "firmware" / "cardputer" / "src" / "c3s_brain.h"
TYPES = {"DNp01": 0, "LC4": 1, "LPLC2": 2}


def main() -> None:
    meta = json.loads(SKEL_JSON.read_text())
    raw = SKEL_BIN.read_bytes()
    lay = meta["layout"]
    pts = np.frombuffer(raw, dtype="<f4", count=lay["points"] * 3).reshape(-1, 3)
    segs = np.frombuffer(raw, dtype="<u4", count=lay["segments"] * 2, offset=lay["segments_byte_offset"]).reshape(-1, 2)
    assert len(pts) < 65536, "segment indices are stored as uint16"
    assert np.abs(pts).max() <= 1.0 + 1e-6

    q = np.clip(np.rint(pts * 127), -127, 127).astype(np.int8)

    cells = []
    for c in meta["cells"]:
        cells.append((TYPES[c["type"]], 0 if c["side"] == "L" else 1, c["first_segment"], c["segments"]))

    def population(side: str) -> np.ndarray:
        idx = []
        for c in meta["cells"]:
            if c["type"] in ("LC4", "LPLC2") and c["side"] == side:
                s = segs[c["first_segment"] : c["first_segment"] + c["segments"]]
                idx.append(np.unique(s.ravel()))
        return pts[np.concatenate(idx)]

    ellipses = []  # cx, cy, cz, rx, ry
    lobes = {}
    for side in ("L", "R"):
        p = population(side)
        mean, sd = p.mean(0), p.std(0)
        lobes[side] = (mean, sd)
        ellipses.append((mean[0], mean[1], mean[2], 2.5 * sd[0], 2.5 * sd[1]))
    (ml, sl), (mr, sr) = lobes["L"], lobes["R"]
    cz = (ml[2] + mr[2]) / 2
    inner = min(abs(ml[0]) - 2.5 * sl[0], abs(mr[0]) - 2.5 * sr[0])
    gf = []
    for c in meta["cells"]:
        if c["type"] == "DNp01":
            s = segs[c["first_segment"] : c["first_segment"] + c["segments"]]
            gf.append(pts[np.unique(s.ravel())])
    gf = np.concatenate(gf)
    slab = gf[np.abs(gf[:, 2] - cz) < 0.25]
    cy = (slab[:, 1].min() + slab[:, 1].max()) / 2
    ry = (slab[:, 1].max() - slab[:, 1].min()) / 2
    ellipses.append(((ml[0] + mr[0]) / 2, cy, cz, max(inner, 0.2), ry))

    lines = [
        "// Generated by scripts/build_firmware_brain.py from docs/sim/skeletons.{bin,json}. Do not edit.",
        "// 26 cells from MaleCNS v1.0 (CC-BY, see NOTICE): both giant fibers (DNp01) and per fiber",
        "// its six strongest LC4 and LPLC2 inputs. Unit-box positions quantised to int8.",
        f"// source sha256: skeletons.bin {hashlib.sha256(raw).hexdigest()}",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define C3S_BRAIN_POINTS {len(q)}",
        f"#define C3S_BRAIN_SEGMENTS {len(segs)}",
        f"#define C3S_BRAIN_CELLS {len(cells)}",
        "",
        "// type: 0 giant fiber (DNp01), 1 LC4, 2 LPLC2; side: 0 left, 1 right (the release's)",
        "typedef struct { uint8_t type, side; uint16_t first_segment, segments; } c3s_brain_cell;",
        "typedef struct { float cx, cy, cz, rx, ry; } c3s_brain_ellipse;",
        "",
        "static const c3s_brain_cell c3s_brain_cells[C3S_BRAIN_CELLS] = {",
    ]
    lines += [f"  {{{t}, {s}, {f}, {n}}}," for t, s, f, n in cells]
    lines += ["};", "", "// left lobe, right lobe, between them: derived from the cells above, not a mesh",
              "static const c3s_brain_ellipse c3s_brain_outline[3] = {"]
    lines += [f"  {{{e[0]:.4f}f, {e[1]:.4f}f, {e[2]:.4f}f, {e[3]:.4f}f, {e[4]:.4f}f}}," for e in ellipses]
    lines += ["};", "", "static const int8_t c3s_brain_points[C3S_BRAIN_POINTS * 3] = {"]
    flat = q.ravel().tolist()
    for i in range(0, len(flat), 24):
        lines.append("  " + ", ".join(str(v) for v in flat[i : i + 24]) + ",")
    lines += ["};", "", "static const uint16_t c3s_brain_segments[C3S_BRAIN_SEGMENTS * 2] = {"]
    flat = segs.ravel().tolist()
    for i in range(0, len(flat), 20):
        lines.append("  " + ", ".join(str(v) for v in flat[i : i + 20]) + ",")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(cells)} cells, {len(q)} points, {len(segs)} segments")
    for name, e in zip(("left lobe", "right lobe", "between"), ellipses):
        print(f"  {name}: centre ({e[0]:+.2f}, {e[1]:+.2f}, {e[2]:+.2f}) radii ({e[3]:.2f}, {e[4]:.2f})")


if __name__ == "__main__":
    main()
