/* Generated by scripts/build_firmware.py from the data block of docs/demo/index.html. Do not edit. */
#ifndef C3S_DATA_H
#define C3S_DATA_H

#include "c3s_core.h"

#define C3S_CORE_NAME        "core-hand-abc"
#define C3S_CORE_INPUTS      17
#define C3S_CORE_OUTPUTS     2
#define C3S_CORE_LATCHES     6
#define C3S_CORE_NAND        173
#define C3S_CORE_DEPTH       25
#define C3S_CORE_BYTES       1235
#define C3S_CORE_SHA256      "7c8eaf62495908c434206ff54aa1f3e9146b4295506f59584d6107d2104b2e52"
#define C3S_POLICY_NAME      "policy-hand-abc"
#define C3S_POLICY_INPUTS    16
#define C3S_POLICY_OUTPUTS   2
#define C3S_POLICY_LATCHES   0
#define C3S_POLICY_NAND      74
#define C3S_POLICY_DEPTH     11
#define C3S_POLICY_BYTES     518
#define C3S_POLICY_SHA256    "03f7f8dc8a53e318871ec85e5160e0ed6e04568f3a1c2ad4ceec904b10a1d3bf"
#define C3S_BITS             4
#define C3S_LEVELS           16
#define C3S_FEATURES         16
#define C3S_RAISE_BITS       3
#define C3S_REFRACTORY_BITS  3
#define C3S_WING_RAISE_TICKS 4
#define C3S_REFRACTORY_TICKS 7
#define C3S_TICK_MS          5.0
#define C3S_START_DEG        10.0
#define C3S_END_DEG          170.0
#define C3S_OVERLAP_DEG      30.0
#define C3S_EPISODES         3

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t c3s_core_netlist[C3S_CORE_BYTES];
extern const uint8_t c3s_policy_netlist[C3S_POLICY_BYTES];
extern const double c3s_size_edges[C3S_LEVELS];
extern const double c3s_speed_edges[C3S_LEVELS];
extern const c3s_ref_episode c3s_episodes[C3S_EPISODES];
extern const char *const c3s_motor_names[4];

#ifdef __cplusplus
}
#endif

#endif
